ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Hotdog!

Hotdog is a syslog-to-Kafka forwarder which aims to get log entries into
link:https://kafka.apache.org[Apache Kafka]
as quickly as possible.


[source,bash]
----
Hotdog 0.1.0
R Tyler Croy <rtyler@brokenco.de
Forward syslog over to Kafka with ease

USAGE:
    hotdog [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -c, --config <FILE>       Sets a custom config file [default: hotdog.yml]
    -t, --test <TEST_FILE>    Test a log file against the configured rules
----

[[configuration]]
== Configuration

Hotdog is configured by the `hotdog.yml` file, which has a very fluid syntax at
the moment. The two main sections are the `global` and `rules` blocks.


Rules defined in the configuration can be tested against an example log file in
order to verify that the right rules are matching the expected log inputs, for
example:

[source,bash]
----
❯ RUST_LOG=info ./target/debug/hotdog -t example.log
Line 1 matches on:
         - ^hello\s+(?P<name>\w+)?
         - .*
Line 2 matches on:
         - .*
Line 3 matches on:
         - .*
Line 4 matches on:
         - ^\{(.*)?\}$
         - .*

----

[[global]]
=== Global

The `global` configuration configures `hotdog` itself. The <<yml-listen,
`listen`>>, <<yml-kafka, `kafka`>>, and <<yml-metrics, `metrics`>> keys are all
required by default in order for `hotdog` to start properly.

[[yml-listen]]
==== Listen

The `global.listen` configuration is required and will determine on which
address and port `hotdog` will listen. The <<yml-listen-tls, `tls`>>
configuration key is required to function as well. When `tls` is left blank,
`hotdog` will listen for syslog messages in plaintext on the specified `port`.

.hotdog.yml
[source,yaml]
----
global:
  listen:
    address: '127.0.0.1'
    port: 1514
    tls:
----

[[yml-listen-tls]]
===== TLS

The `global.listen.tls` configuration section can be used to enable
syslog-over-TLS support from `hotdog`. Currently the only two valid keys for
this section are `cert` and `key`, both of which should be absolute or relative
paths to PEM-encoded files on disk.

Certificate and Key files can be created with `certtool --generate-privkey
--outfile ca-key.pem`


[[yml-kafka]]
==== Kafka

A `global.kafka` configuration is required in order for `hotdog` to function
properly. The two main configuration values are <<yml-kafka-conf, `conf`>> and <<yml-kafka-topic, `topic`>>.

.hotdog.yml
[source,yaml]
----
global:
  kafka:
    conf:
      bootstrap.servers: 'localhost:9092'
      client.id: 'hotdog'
    topic: 'logs'
----

[[yml-kafka-conf]]
===== Conf

`global.kafka.conf` should contain a map of
link:https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md[librdkafka configuration values].
`hotdog` will expect every key _and_ value to be a String. These configuration
values are passed right on to the underlying librdkafka client connection, so
whatever librdkafka supports, `hotdog` supports!


[[yml-metrics]]
==== Metrics

The `global.metrics` configuration tells `hotdog` where to send its own
internal metrics  The only _currently_ supported metrics format is
link:https://github.com/statsd/statsd[statsd].

If your environment doesn't use statsd or you do not wish to report metrics,
set the `statsd` value to an invalid host and port.

.hotdog.yml
[source,yaml]
----
global:
  metrics:
    statsd: 'localhost:8125'
----


[[rules]]
=== Rules

Hotdog's rules define how it should handle and route the syslog messages it
receives.

[[actions]]
==== Actions

Actions determine what `hotdog` should do with the given log line when it
receives it. 

[[variables]]
Some actions, such as <<action-replace>>, can perform variable substitutions on
log line. The variables available are a combination of the built-in variables
listed below, and whatever named groups exist in the `regex` field of the
<<rules>>.

[CAUTION]
====
Named groups will **override** any built-in variables at the time of
substitution, so be careful you are not naming your groups anything which might
overlap with the built-in variable names
====

[[builtin-vars]]
.Built-in Variables
|===
| Name | Description

| `msg`
| The original log line message sent along from the syslog sender.

|===

[[action-forward]]
===== Forward

The forward action will imply the <<action-stop, Stop action>> when used.


[[action-merge]]
===== Merge

.Parameters
|===
| Key | Value

| `json`
| A YAMl map which will be merged with the JSON object deserialized from the matched log line.

|===

The `merge` action will only work when the log line is a JSON **object**. JSON
arrays, or other arbitrary strings will not merge properly, and cause **all**
subsequent actions for the given rule to be aborted.

[[action-replace]]
===== Replace

.Parameters
|===
| Key | Value

| `template`
| A link:https://handlebarsjs.com/[Handlebars]-style template which can be used to output a modified message.

|===

The `template` may utilize the <<variables, matched and built-in variables>> in
order to generate a modified message. The output is only available to
subsequent actions defined _after_ the `replace` action. Subsequent rules in
the chain **will not** utilize this generated message.


[[action-stop]]
===== Stop

[[development]]
== Development

Hotdog is tested against the latest Rust stable. A simple `cargo build` should
compile a working `hotdog` binary for your platform.


On Linux systems it is easy to test with:

[source,bash]
----
logger --server 127.0.0.1  -T -P 1514 "hello world"
logger --server 127.0.0.1  -T -P 1514 -f example.log 
----

For TLS connections, you can use the `openssl` `s_client` command:

[source,bash]
----
echo  '<13>1 2020-04-18T15:16:09.956153-07:00 coconut tyler - - [timeQuality tzKnown="1" isSynced="1" syncAccuracy="505061"] hello world' | openssl s_client -connect localhost:6514
----

